modLoader = "javafml"
loaderVersion = "[36,)"
license = "BSD 3-Clause License"
issueTrackerURL = "https://github.com/Dungeon-Makers/Armour-and-Item/issues" #optional
[[mods]]
modId = "armouranditem"
version = "${file.jarVersion}"
displayName = "Custom Armour and Items"
displayURL = "https://github.com/Dungeon-Makers"
updateJSONURL = "https://raw.githubusercontent.com/Dungeon-Makers/Armour-and-Item/master/update.json"
credits = "Custom Armour and Items by Yusuf Arfan Ismail."
authors = "Dungeon Makers" #optional
description = '''
A mod which add custom armour and items.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.armouranditem]] #optional

modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.armouranditem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"



