
modLoader="javafml"
loaderVersion="[36,)"
license="BSD 3-Clause License"
[[mods]]
modId="armouranditem"
version="${1}"
displayName="Custom Armour and Items"
credits="Custom Armour and Items by Yusuf Ismail."

authors="Yusuf Ismail" #optional
description='''
A mod which add custom armour and items.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.armouranditem]] #optional

    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armouranditem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"




