modLoader = "javafml"
loaderVersion = "[38,)"
license = "BSD 3-Clause License"
issueTrackerURL = "https://github.com/Dungeon-Makers/Armour-and-Item/issues" #optional
[[mods]]
modId = "armouranditem"
version = "${file.jarVersion}"
displayName = "Custom Armour and Items"
displayURL = "https://github.com/Dungeon-Makers"
updateJSONURL = "https://raw.githubusercontent.com/Dungeon-Makers/Armour-and-Item/master/update.json"
credits = "Custom Armour and Items by Yusuf Arfan Ismail."
authors = "Dungeon Makers" #optional
description = '''
A mod which add custom armour and items.
'''

[[dependencies.armouranditem]] #optional
modId = "forge"
mandatory = true
versionRange = "[38.0.16,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.armouranditem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18, 1.19)"
ordering = "NONE"
side = "BOTH"



